# Generated by Django 2.0.3 on 2018-03-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20180313_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercontent',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AlterField(
            model_name='usercontent',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
