# Generated by Django 2.0.3 on 2018-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20180314_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcomment',
            name='message',
            field=models.TextField(max_length=100),
        ),
    ]
