# Generated by Django 2.0.3 on 2018-03-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedsocialuser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='feedsocialuser',
            unique_together={('username',)},
        ),
    ]
